obj-y := gpu_sysfs.o

# Common files.
gpu_sysfs-y :=	gpu_sysfs_main.o \
		        gpu_sysfs_util.o


# Platform specific files.


# ==================================
# Start --------- Qualcomm ---------
ifeq ($(CONFIG_MSM_KGSL),y)

gpu_sysfs-y +=	gpu_sysfs_target_kgsl.o

endif
# End ---------- Qualcomm ----------
# ==================================
